### ISSUE TITLE
the two models, classifier.ckpt and detector.ckpt, are the final models?

### ISSUE THREAD

**Issue by raymon-tian** [lfz/DSB2017#24] opened 2017-06-10 09:42 UTC
if not, could you upload the two models? 
Thanks. :)

**Comment by galactica147** [comment] 2017-06-22 21:22
i think they're the pre-trained models, because I'm able to reproduce the winning score using these two models.

**Comment by raymon-tian** [comment] 2017-06-29 03:16
Thanks :)

**Comment by raymon-tian** [comment] 2017-06-29 03:17
@galactica147 Thanks :)

**Comment by bfan1256** [comment] 2017-12-11 02:14
If this has been answered, can you please close it @raymon-tian ?

**Comment by nishat0403** [comment] 2018-06-23 19:15
@galactica147 how did you manage to run the code? The stage1 dataset provided by Kaggle is not available anymore. Do you have a copy of the dataset? It would be really helpful if you share it at nishatsayyed26@gmail.com
And can you please briefly describe how you executed the code? I mean the sequence of files you executed and other things. I am researching on this so, ut would be really helpful.
Thank you.

**Closed** 2018-06-27 09:00 UTC
